### PR TITLE
Add Windows Support

### PR DESCRIPTION
**Pull request by walexnelson**
fixes issue #26

### CODE REVIEW

**Comment by jpumford** [comment]
Thanks for this @walexnelson!

I just had a few questions... Is there a reason we're locking down our angular dependencies? Was there an issue you ran into?

To make sure our framework stays the same, you can make the cross-env PR on starter-kit, and then we can run `update-tools` on this repo. I think it would help things stay cleaner. I don't mind running the `update-tools` myself since that can get pretty gnarly.

**Comment by walexnelson** [comment]
I was running into issues because we're pulling angular and some angular libraries via CDN so we're always getting version 1.5.3. But other angular libraries via NPM were `^1.5.3` so npm would install some versions that didn't match. The specific one I ran into was an issue with Angular Material and Angular Animate not matching. I referenced the issue in that commit message if you want to check it out. 

But it may be a non issue if I put this `cross-env` on the starter kit assuming no one has run into angular dependencies with the starter kit.

**Comment by jpumford** [comment]
Oh, you're totally right. I think we fixed this in starter-kit but not in the sample app.
Sorry, I should have looked to see if there was a commit message. Thanks for putting that in there!

I'll run update-tools and then clean up this repos dependencies. If you want to make this PR on starter-kit so we can use `cross-env` that would be awesome!

**Comment by walexnelson** [comment]
cool. I just created the pull request [starter-kit#68](https://github.com/DomoApps/starter-kit/pull/68).

**Comment by sldavidson** [comment]
Going to pulled these changes in with #28.

**Pull request closed without merging**
